Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false # 有効にすると見た目がいいレイアウトにした際に怒られるため無効にする
  # EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: false # 有効にすると見た目がいいレイアウトにした際に怒られるため無効にする
  # EnforcedStyleForMultiline: consistent_comma

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 250 # 数字に特に根拠はない

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '()'
    '%W': '[]'

Style/Documentation:
  Enabled: false # 一行目に class って書いてもいいでしょ

Style/ClassAndModuleChildren:
  Enabled: false # 暫定的に false にする（名前空間関連）

Metrics/MethodLength:
  Enabled: false # メソッドの長さが長いと怒られる（有用なので後で調整すること）

Metrics/AbcSize:
  Max: 20 # これぐらいの長さになることは許してほしい

Style/RegexpLiteral:
  Enabled: false # 有効にすると Lint/Syntax で怒られる？ので無効化

# 頃合いを見て true に変更する
Gemspec/RequiredRubyVersion:
  Enabled: false
